### PR TITLE
Add setup.py

### PR DESCRIPTION
**Pull request by xylar**
This will support Windows properly and allow conda-tree to be added to conda-forge.

See https://github.com/conda-forge/staged-recipes/pull/8347

### CODE REVIEW

**Comment by xylar** [comment]
I bumped the version number on the assumption that there would need to be a new release (for conda-forge) once this is added.

As you probably know, you can test the build by first changing:
```
source:
  path: .
  #git_url: https://github.com/rvalieris/conda-tree.git
  #git_rev: v0.0.3
```
and then running:
```
conda build meta.yaml
```
That worked great for me locally with Ubuntu and python 3.7.

**Comment by xylar** [comment]
Obviously, if this PR is not welcome, just let me know.  I can include these changes as a patch on conda-forge if necessary but it's always best to make these changes in the original repo if possible.

**Comment by rvalieris** [comment]
looks good, thanks.

**Comment by xylar** [comment]
Thanks so much!  Could you make a 0.0.3 release as well, so I can use that on conda-forge.

**Comment by xylar** [comment]
Thanks very much!

**Pull request merged**
